-- Users Table
-- NOTE: ID is running from 1, 2, 3, ...
CREATE TABLE users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	email VARCHAR(255),
	username VARCHAR(255),
	description TEXT,
	password VARCHAR(255),
	gender VARCHAR(10),
	image TEXT,
	date_joined DATE,
	last_login DATE
);

COPY users (first_name, last_name, email, username, description, password, gender, image, date_joined, last_login)
FROM 'D:/Projects/board_log/dev/sql_commands/dev_users.csv' 
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- Groups Table
CREATE TABLE groups (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	name VARCHAR(255),
	description TEXT,
	date_created DATE,
	last_updated DATE,
	games_played INT
);

COPY groups (name, description, date_created, last_updated, games_played)
FROM 'D:/Projects/board_log/dev/sql_commands/dev_groups.csv' 
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- User_group Table
-- TODO: Need to add foreign key constraint and cascade rule
CREATE TABLE user_group (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint,
	group_id UUID
);

COPY user_group (user_id, group_id)
FROM 'D:/Projects/board_log/dev/sql_commands/dev_user_group.csv' 
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- Comp Game Log
CREATE TABLE comp_game_log (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id VARCHAR(11),
	date_played DATE,
	game_id INT,
	game_title VARCHAR(255),
	game_weight DECIMAL,
	game_length INT,
	num_players INT,
	user_id BIGINT,
	username VARCHAR(255),
	group_id UUID,
	group_name VARCHAR(255),
	is_vp BOOLEAN,
	victory_points INT,
	is_winner BOOLEAN,
	position INT,
	win_contrib INT,
	score DECIMAL,
	high_score BOOLEAN,
	quarter INT,
	month INT,
	year INT
);

COPY comp_game_log (session_id, date_played, game_id, game_title, game_weight, game_length, num_players, user_id,username,group_id,group_name,is_vp,victory_points,is_winner,position,win_contrib, score,high_score,quarter,month,year)
FROM 'D:/Projects/board_log/dev/sql_commands/comp_game_log.csv' 
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');


INSERT INTO users (first_name, last_name, email, username, description, password, gender, image, date_joined, last_login) VALUES (
	'martin',
	'ho',
	'mho@email.com',
	'mho',
	'hello',
	'pass',
	'Male',
	'img.com',
	'13-08-2025',
	'12-08-2025'
);